/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class JsLayerPack {
  constructor(path: string)
  get name(): string
  get author(): string | null
  getFileList(): Array<string>
  readFile(path: string): Buffer
}
